language: python

python:
  - '3.4'

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
before_script:
  - cd tests
script:
  - python -m unittest discover -v

after_success:
  - coveralls